################################# Default configuration ###################
baseURL = "https://sleepy-lamport-30d913.netlify.app/"
title = "History Boys Japan"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
defaultContentLanguage = 'ja'
summaryLength = "2"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
[markup]
defaultMarkdownHandler = 'blackFriday'
[blackFriday]
hrefTargetBlank = true


############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Anton&family=Fjalla+One&family=Zen+Antique&family=Zen+Antique+Soft&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### Japanese Navigation ########################

[[Languages.ja.menu.main]]
name = "Story"
url = "#story"
weight = 1

[[Languages.ja.menu.main]]
name = "Cast"
url = "#cast"
weight = 2

[[Languages.ja.menu.main]]
name = "Staff"
url = "#staff"
weight = 3

[[Languages.ja.menu.main]]
name = "Tickets & Access"
url = "#feature"
weight = 4

[[Languages.ja.menu.main]]
name = "Toho"
url = "/"
weight = 5

################### English Navigation ########################

[[Languages.en.menu.main]]
name = "Story"
url = "#story"
weight = 1

[[Languages.en.menu.main]]
name = "Cast"
url = "#cast"
weight = 2

[[Languages.en.menu.main]]
name = "Staff"
url = "#staff"
weight = 3

[[Languages.en.menu.main]]
name = "Tickets & Access"
url = "#feature"
weight = 4

[[Languages.en.menu.main]]
name = "Toho"
url = "/"
weight = 5

############################# Default Parameters ##########################
[params]
# logo = "images/logo.png"
# Meta data
description = "The History Boys Japan Website"
author = "Tomo Norman"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = false

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "35.71598956887827"
map_longitude = "139.6936238188775"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

################################ Japanese Language ########################
[Languages.ja]
languageName = "Jp"
languageCode = "ja-jp"
contentDir = "content/japanese"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2022 Tomo Norman"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2022 Tomo Norman"
